### ISSUE TITLE
Please add to stable repository if shown working for users

### ISSUE THREAD

**Issue by Apollon77** [UncleSamSwiss/ioBroker.i2c#8] opened 2018-08-27 10:14 UTC

**Comment by UncleSamSwiss** [comment] 2019-01-12 16:35
There are some issues (one PR I'm not sure if it is OK --> to be verified) and some more device I would like to add before making this adapter official.
I ordered some hardware and will be adding the devices in the coming months.

**Comment by UncleSamSwiss** [comment] 2019-01-12 16:36
Depends on #7, #10, #11, #12, #13

**Comment by UncleSamSwiss** [comment] 2020-11-02 16:32
Duplicate of #39

**Closed by UncleSamSwiss** 2020-11-02 16:32 UTC
Labels: enhancement
